apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logalert.fullname" . }}-config
  labels:
    {{- include "logalert.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "is_debug": {{ .Values.app.debug_mode }},
      "storage": {
        "host": "{{ .Values.app.storage.host }}",
        "port": {{ .Values.app.storage.port }},
        "index_name": "{{ .Values.app.storage.index_name }}",
        "api_prefix": "{{ .Values.app.storage.api_prefix }}"
      },
      "watch_interval": {{ .Values.app.watch_interval }},
      "query_string": "{{ .Values.app.query_string }}",
      "slack": {
        "webhook_url": "{{ .Values.app.slack.webhook_url }}"
      }
    }
