apiVersion: v1
kind: Service
metadata:
  name: {{ include "logalert.fullname" . }}
  labels:
    {{- include "logalert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "logalert.selectorLabels" . | nindent 4 }}
